        IDENTIFICATION DIVISION.
        PROGRAM-ID. QR.
        PROCEDURE DIVISION.
        DISPLAY
            "(f=(n)->Array(n+1).join '\\');console.log('%s"&
            "',(""(write-line\""import std.stdio;void main()"&
            "{write(\x60method Main(){print(@#{f(1)}\""[cla"&
            "ss QR:Application{void f(String const s,int n"&
            "){for(Print(s);n;n--)Print(#{f(1)}\""#{f(1)}\"""&
            "#{f(5)}\""#{f(1)}\"");}void Main(){f(#{f(1)}\""#"&
            "{f(1)}\""IO.puts(#{f(3)}\""#{f(1)}\""(princ #{f("&
            "1)}\""#{f(1)}\"",1);f(#{f(1)}\""#{f(1)}\""#{f(3)}"&
            "\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",2);f(#{f(1)}\""#"&
            "{f(1)}\""nmain(_)->#{f(1)}\""#{f(1)}\"",2);f(#{f"&
            "(1)}\""#{f(1)}\""nio:fwrite(#{f(1)}\""#{f(1)}\"","&
            "3);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""prin"&
            "tfn(#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\"&
            """#{f(3)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",7);f(#{"&
            "f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""#{f(1)}\""#{"&
            "f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1"&
            ")}\""#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\"&
            """#{f(3)}\""#{f(1)}\"" : A .#{f(1)}\""#{f(1)}\"",7"&
            ");f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{"&
            "f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3"&
            ")}\""#{f(1)}\""         #{f(1)}\""#{f(1)}\"",7);f"&
            "(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1"&
            ")}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\"&
            """#{f(1)}\"" ; : B A .#{f(1)}\""#{f(1)}\"",7);f(#"&
            "{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}"&
            "\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#"&
            "{f(1)}\"" WRITE(*,*)'#{f(1)}\""#{f(1)}\"",7);f(#"&
            "{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}"&
            "\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#"&
            "{f(1)}\"" A ; : C B TYPE .#{f(1)}\""#{f(1)}\"",7"&
            ");f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{"&
            "f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3"&
            ")}\""#{f(1)}\"" '#{f(1)}\""#{f(1)}\"",7);f(#{f(1)"&
            "}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f"&
            "(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)"&
            "}\"" CR ; : D S#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}"&
            "\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f("&
            "1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}"&
            "\"" program QR#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\"&
            """#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1"&
            ")}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"&
            """ C S#{f(1)}\""#{f(1)}\"",15);f(#{f(1)}\""#{f(1)"&
            "}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7)"&
            ";f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"" print"&
            " #{f(1)}\""#{f(1)}\"",15);f(#{f(1)}\""#{f(1)}\""#"&
            "{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#"&
            "{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""(&#{f(1)}\"&
            """#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{"&
            "f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{"&
            "f(1)}\""#{f(3)}\""#{f(1)}\"" C S#{f(1)}\""#{f(1)}"&
            "\"",15);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"""&
            "34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\"""&
            "#{f(3)}\""#{f(1)}\"" print#{f(1)}\""#{f(1)}\"",15"&
            ");f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{"&
            "f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3"&
            ")}\""#{f(1)}\""s:=OutputTextUser();WriteAll(s,("&
            "#{f(1)}\""#{f(1)}\"",31);f(#{f(1)}\""#{f(1)}\""#{"&
            "f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{"&
            "f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""printn(#{f("&
            "1)}\""#{f(1)}\"",63);f(#{f(1)}\""#{f(1)}\""#{f(3)"&
            "}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)"&
            "}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""set print#{f(1)"&
            "}\""#{f(1)}\"",127);f(#{f(1)}\""#{f(1)}\""#{f(3)}"&
            "\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}"&
            "\""#{f(1)}\""#{f(3)}\""#{f(1)}\""-#{f(1)}\""#{f(1)"&
            "}\"",127);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}"&
            "\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}"&
            "\""#{f(3)}\""#{f(1)}\"";print(#{f(1)}\""#{f(1)}\"""&
            ",127);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""3"&
            "4,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#"&
            "{f(3)}\""#{f(1)}\""package main;import(F#{f(1)}"&
            "\""#{f(1)}\"",255);f(#{f(1)}\""#{f(1)}\""#{f(3)}\"&
            """#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\"&
            """#{f(1)}\""#{f(3)}\""#{f(1)}\""fmt#{f(1)}\""#{f(1"&
            ")}\"",255);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)"&
            "}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)"&
            "}\""#{f(3)}\""#{f(1)}\"";S#{f(1)}\""#{f(1)}\"",255"&
            ");f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{"&
            "f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3"&
            ")}\""#{f(1)}\""strings#{f(1)}\""#{f(1)}\"",255);f"&
            "(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1"&
            ")}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\"&
            """#{f(1)}\"");func t(s string)string{r:=#{f(1)}"&
            "\""#{f(1)}\"",255);f(#{f(1)}\""#{f(1)}\""#{f(3)}\"&
            """#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\"&
            """#{f(1)}\""#{f(3)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"&
            """,255);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"""&
            "34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\"""&
            "#{f(3)}\""#{f(1)}\"";for i,n:=range s{if n<48{r"&
            "+=#{f(1)}\""#{f(1)}\"",255);f(#{f(1)}\""#{f(1)}\"&
            """#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f"&
            "(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""v#{f(1)}"&
            "\""#{f(1)}\"",255);f(#{f(1)}\""#{f(1)}\""#{f(3)}\"&
            """#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\"&
            """#{f(1)}\""#{f(3)}\""#{f(1)}\""}else{r+=S.Repeat"&
            "(#{f(1)}\""#{f(1)}\"",255);f(#{f(1)}\""#{f(1)}\"""&
            "#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f("&
            "#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""Ww#{f(1)}"&
            "\""#{f(1)}\"",253);f(#{f(1)}\""#{f(1)}\""#{f(1)}\"&
            """#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{"&
            "f(1)}\"",2);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1"&
            ")}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1"&
            ")}\""#{f(3)}\""#{f(1)}\""[i%%2:i%%2+1],int(n)-48"&
            ")}};return r};func main(){s:=t(#{f(1)}\""#{f(1"&
            ")}\"",255);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)"&
            "}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)"&
            "}\""#{f(3)}\""#{f(1)}\""013141#{f(1)}\""#{f(1)}\"""&
            ",255);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""3"&
            "4,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#"&
            "{f(3)}\""#{f(1)}\"")+S.Repeat(t(#{f(1)}\""#{f(1)"&
            "}\"",255);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}"&
            "\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}"&
            "\""#{f(3)}\""#{f(1)}\""/12131#{f(1)}\""#{f(1)}\"","&
            "255);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34"&
            ",#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{"&
            "f(3)}\""#{f(1)}\""),6)+t(#{f(1)}\""#{f(1)}\"",255"&
            ");f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{"&
            "f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3"&
            ")}\""#{f(1)}\""/1:151419>>5261413/4=3626612/2/3"&
            "53251215/Z0Z0<#{f(1)}\""#{f(1)}\"",255);f(#{f(1"&
            ")}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{"&
            "f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1"&
            ")}\"");for i,n:=range(#{f(1)}\""#{f(1)}\"",255);"&
            "f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f("&
            "1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}"&
            "\""#{f(1)}\""print(#{f(1)}\""#{f(1)}\"",511);f(#{"&
            "f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\"&
            """#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{"&
            "f(1)}\""main=putStr(#{f(1)}\""#{f(1)}\"",1023);f"&
            "(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1"&
            ")}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\"&
            """#{f(1)}\""class QR{public static function mai"&
            "n(){neko.Lib.print(#{f(1)}\""#{f(1)}\"",163);f("&
            "#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);f(#{f"&
            "(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",1884);f(#{f"&
            "(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\"""&
            "#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f"&
            "(1)}\""procedure main();i:=c:=0;s:=(#{f(1)}\""#"&
            "{f(1)}\"",1900);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#"&
            "{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f("&
            "1)}\"",2195);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f("&
            "1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f("&
            "1)}\""#{f(3)}\""#{f(1)}\"".class public QR#{f(1)"&
            "}\""#{f(1)}\"",1602);f(#{f(1)}\""#{f(1)}\""#{f(1)"&
            "}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\"""&
            "#{f(1)}\"",2494);f(#{f(1)}\""#{f(1)}\""n.super j"&
            "ava/io/PrintStream#{f(1)}\""#{f(1)}\"",1304);f("&
            "#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);f(#{f"&
            "(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",2792);f(#{f"&
            "(1)}\""#{f(1)}\""n.method public static main([L"&
            "java/lang/String;)V ;]#{f(1)}\""#{f(1)}\"",981)"&
            ";f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);f("&
            "#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",3115);f("&
            "#{f(1)}\""#{f(1)}\""n.limit stack 2#{f(1)}\""#{f"&
            "(1)}\"",695);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f("&
            "1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}"&
            "\"",3401);f(#{f(1)}\""#{f(1)}\""ngetstatic java/"&
            "lang/System/out Ljava/io/PrintStream;#{f(1)}\"&
            """#{f(1)}\"",371);f(#{f(1)}\""#{f(1)}\""#{f(1)}\"""&
            "#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f"&
            "(1)}\"",3725);f(#{f(1)}\""#{f(1)}\""nldc #{f(1)}"&
            "\""#{f(1)}\"",95);f(#{f(1)}\""#{f(1)}\""#{f(1)}\"""&
            "#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f"&
            "(1)}\"",3825);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f"&
            "(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)"&
            "}\"",3825);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)"&
            "}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"""&
            ",446);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""3"&
            "4,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#"&
            "{f(3)}\""#{f(1)}\""class QR{public static void "&
            "main(String[]v){String c[]=new String[99999],"&
            "y=#{f(1)}\""#{f(1)}\"",3292);f(#{f(1)}\""#{f(1)}"&
            "\""#{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#"&
            "{f(1)}\""#{f(1)}\"",3825);f(#{f(1)}\""#{f(1)}\""#"&
            "{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f("&
            "1)}\""#{f(1)}\"",3825);f(#{f(1)}\""#{f(1)}\""#{f("&
            "1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}"&
            "\""#{f(1)}\"",3825);f(#{f(1)}\""#{f(1)}\""#{f(1)}"&
            "\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#"&
            "{f(1)}\"",1616);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#"&
            "{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#"&
            "{f(1)}\""#{f(3)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"","&
            "2197);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"","&
            "0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",382"&
            "5);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);"&
            "f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",3825);"&
            "f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);f(#"&
            "{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",3825);f(#"&
            "{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);f(#{f("&
            "1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",2711);f(#{f("&
            "1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#"&
            "{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f("&
            "1)}\"",z=y,s=#{f(1)}\""#{f(1)}\"",1095);f(#{f(1)"&
            "}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\"""&
            "#{f(1)}\""#{f(1)}\""#{f(1)}\"",3825);f(#{f(1)}\"""&
            "#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f"&
            "(1)}\""#{f(1)}\""#{f(1)}\"",3825);f(#{f(1)}\""#{f"&
            "(1)}\""#{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)"&
            "}\""#{f(1)}\""#{f(1)}\"",3825);f(#{f(1)}\""#{f(1)"&
            "}\""#{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\"""&
            "#{f(1)}\""#{f(1)}\"",3813);f(#{f(1)}\""#{f(1)}\"""&
            "#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f("&
            "#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""#{f(1)}\"""&
            "#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""bvb.b-b2b.b+"&
            "bxa;b+b.bza5a4a2b2a4a9a5a/a5boa/aNaJb/b1b|b-b"&
            "3aHaNbQbobRb*bscdbRa6aHbna5cbcha/bsbsb2cobqaE"&
            "a7cob|cocjbyb.b1a-b}aJaCaGa:a>aGa=aHb7aJa5aVb"&
            "Ya5bva6aKaKb}a6a2a?a8a>caccbRcgcda/cwcIb*b*cy"&
            "cIbnb7aGb7cCbpa6bxb-bwa6c|c*bva-bXc+b.bXa5bnc"&
            "obfbxbvb3b|b?aUbxbtbwbxb1a8b-btb,bxaGaJbdbeaH"&
            "dmdodqb-bcb4bub+b|bva:b,btbXaIa:cFa/ckcochdCa"&
            "/a1a5b1bxb/b+btbvbxdGdIdKdMa5b2a9dBdCdWbRdUcI"&
            "dXebdXa/a6dZbReba/coegejecedcza6eia;bVbXbZcod"&
            "ba-b2aJd:b3bvb{btb+b+dGcoa;b:a>a9aFaFb<ekd?aM"&
            "ezbzbFbue,bna>a?aDa=aBb7deaEbpbveiaUaNaVa-a>a"&
            ";a?eca=aNbiaVbfaVaOaYaRa-eca?a?c5b2b3bWb-bza;"&
            "bzb2d4a5a5aGfda?e,b+aGfsebaBaPb-ajaMdnb{b.a-a"&
            "4d6b-bxfwaGe5f6aHetc9ecf{fydXfebAb+b5bxeybtdp"&
            "b2byb8aHb.b4b3b/fLa-cla3a>a3f;aPf=dWfea;btb2b"&
            "2bxb,d5b8a-b3b:b<a;d|b3f-bwa-fNd5d7eyb3fEgtb5"&
            "dhgpaZd;b-a5a6b:a;cXfib8b/dhbYa-b+bwfhb1a3a@f"&
            "TfzfVftb,fxbwbucHcda1dCa1f9b3a5fRaBg<dXf<ftgI"&
            "bygKa@fSfUfWdCfef,b.gKaCg;gWfta0b|b,g2b1b3aIf"&
            "hbwdqa;b{aKa3aCaAa3b-eua-d:dig,fNb3b2gKeAaDgN"&
            "dWgPebfegIbrg8bXbHa3a?aBgMhfh4a?ezb3b.gabvb|b"&
            "|gKaBa>gVg=gXchh5fjgJfRa=a?hehMgQb1bGb1d{a-d,"&
            "a5fKfMfLcjbubxbzdfb6bWb3dNa4fRa3a4a4b2a8a8bra"&
            "8aHiwa8e*c*a@aCa8bxi|ixa9i{i}i+a-a@aFi/i1i*b{"&
            "c*aAcBi0i}aOi4ixi6i8i:i}bxb5e,gqdLb*iDi<c*aBi"&
            "9iAixikiPi6eAaAiHi2cBi;i6aAa>jba8aCa:jgiXi=a-"&
            "i?jijfjhiUdya<a@jdi5joi-jrjoaAa=jib-a:eujni,i"&
            ".juaOaEa9i+j1jpj,jufobug8a-b4b-b/irfSiua9jDit"&
            "a4iNj9iSj}i,aEjNi7j3i;c}bwj9aCjti;b-j9j|juiYa"&
            "?jajua;j9iZjiiwjejojMkdj{kgi;aEaAb6b7aEb-b*b9"&
            "bdaBbib*aDa>aSb4aQeLbyaEaCbdb7bybuaEbzbyaTbhb"&
            "lb+b,bhbjgeaRbhb|bdbvbvgBbeb,b*btaVbvbja>bkb,"&
            "b6b}fxkUbmb6bwfia<bhaQaTb7b-aFaCb,bwfxe<b6aFa"&
            "XaSbmb{buaAb,aPbjbVbdbzaEbmaFaAb*bubuaTa=bkaD"&
            "aNbxaFbjbjb3jHjFl;a4bxbcb6kIaXb2bwb-aZaYblbhb"&
            "kbhb4aPbiaBb4aFaEaXb*bhl0a=bzl4kIbjbtbab|aDfx"&
            "buf6bcb8geaSbzbcbja@kQb1b{b7kCb*kQb+bua=blaNb"&
            "dbmbdk=bab*k=bmkLbia>k1blg@aGlblxb0k6b2bjb4bf"&
            "bdbkb}aRbdkAm.m0m,biaPk1a@b*gAb3lxb7aQaEbaaUb"&
            "1b/bdb1b}bzb5aNb3a>b}a?b8aNaYbeb+fVaGa@aDbyaQ"&
            "b9lvaSmVmXbWaSk9a@bya<b1aQb5blbbaPaSb+aXaRb7b"&
            "7bdhCk1nibfn+d,aFbab.aFb1aTbyaPb0lsbabub4b0b-"&
            "b}bmb-b1a>b6b|bfb-a@bzblgabxaNbkaVb/gdb7b{gBb"&
            "mbwbabgaTaRc8b0bgm|bfaRaEbwbkbgaPb/a@n5bdl=jG"&
            "isiun8aUb8aRn;aQn=baa>aFb3bbotikb5aVbkb0bhbva"&
            "YaSmXngaEbvaAaZo|b3bifxaCbwb5k6b*b}lRaEo6bkaR"&
            "beaFb,b8btaZaTb}a<bla>bcb+bbaYbwbmfxb-aEb7b}i"&
            "jnDb.aNkxaYkHaViab|baaXdhaRb0b7kGp/e<m1kMbtaX"&
            "babla@pxaRb,bvb9fxbkb|aRaSaFo/bcm;aWbcaYb5bkb"&
            "vaEa=aCaQbab{bkpGhCbyaYaTb9pGbbb8p9oIbtb1aSbv"&
            "dKb/bwbfa>aAbubgbtaEb}beb0kAp9b,blbdaPlXbbbea"&
            "Bb|lGaSbwaZb4a=b,bda?mWb-k9b5bebxk=aXb1aDmeaX"&
            "bvaCb0aYaPbtbgndbxbgaBkwbfb3bcaAbcmVaUb,aYaQp"&
            "kpmpoaGbuaRbba?o*l=msb6plb+b}aXb0oIbdb/ogfxa?"&
            "aEbeoBaDb7b,aXpxbcrsbtb8b-bBnEb.b6aZb,g|aFaBb"&
            ".b7aZnLaUbabjlvbebkb/b|nAaZoPb7d6fxa>bibxaEaU"&
            "aDb/aObjblb|l/aDbwolb+b0a?aZrmg|qDbeaCpLbgbyh"&
            "kb5b7a=bdaCa=n-bybbbjr7q0mYeBbfpKa<a<lQaTb{bj"&
            "pIbabab3b}bglzkvaNa?bza<b+beaVaAaXb3lFb1ouspa"&
            "Sb8bdb+bib1aPnIaSnXaTb4aXbyb2a>nHaYb*kwaObbaF"&
            "a@bmb|bea>hCbmbtb7aUaTbudpb|aBaXbcb|b9mSb6b6b"&
            "unObzbmaNbbbbb2tdaBa@p<aClsaFaNbzb1oMsTaVb.hF"&
            "b|aYa<bvbab}l2k1b2bvrho,a4bda>bhlib3bfb/aZb3b"&
            "mbbbka>bBbgbka=b8bvaBaQs8b4fxb8bcb7aAqIbub{b|"&
            "bgaYb3oPb.bwtYaYa?bxsgb4aNp7pBbcbzfab}b0a@b4b"&
            "{e}b1s*aAfxs4b1a=bcaCupmgb/b8b*aAbabcb5a=bgb0"&
            "bcbfbabbnXaSbca<b}k8bcaNbcbkaPb,jXbbbdaAb8g|a"&
            "WbuaDaYb4s,rMaOmjbee<b|aPaXaPbmaQbhoqtNaPblre"&
            "bgbzdpfxaBblbzb.aVaBb9aUb0aEbxa=b1aRb4b.b.aOb"&
            "vbdbjbhb+aNa>blb4q0beb8aSaXaBbfbgb{a@k+aBsOub"&
            "b7b2bcaXb,aTaUb-uFbeb{bebYben0aNaTb2b*vxk{aQb"&
            "kk{bfaBb/bzfxbaaEouo7qQa<b7t>bgb*aNbgbuaSb3k}"&
            "aVtEjEa4b7blpYb7tevSbdqwaSsZuipRaCbkmgbid2aCa"&
            "TaSaQb@b6bfaCaObzaPbwwwaFr9b7w-bib{bcaBs@sKwE"&
            "bca?nFbbt0b.q6bvkWaGb1bexob,fiaNb,b4aYbakUe-a"&
            "?blb}b|a?biaUaUa>b7s=s?q9rowIbkb+b2w<b*b4bco8"&
            "b>u:b{b9a=biblpRaAb.b}pYaSppb2b6blbmaXblwMwOs"&
            "KlspJeBq,aVw,bybmb.buo>xJaGb3a@b8mSbvb,aNaWb{"&
            "a?aSa@aAaVaRaWb|aTbvlIbzbubcybwRaEb3bwaFa=btl"&
            "vb3aDbfhjb7n;aSb2sgb/n-b|b*a>beb6oFoqaAblpdb3"&
            "aVxHaSolaXb6b5b9tibkbabfbfbiw-lwb/bcw3jImup+b"&
            "dyWblyFyHyJoByMnRaVaFyWx.aAbmk9aEblaXb4aEbbb*"&
            "a<aNbmaWrsaUaWaAwwaUblbeu/b1b2ymbkaZbyaBb-c8v"&
            "}aBb1bfbjmnaOz9bzaZbwbbb1pdb|aNaNbyb3lQrmaXv}"&
            "aPzKbjzMnnzQaFb+bzb0aOaTbFaPq=aTb#{f(1)}\""#{f"&
            "(1)}\"",0);f(#{f(1)}\""#{f(1)}\""agAaDlRa@l3aCna"&
            "aAg6lUb0b+bmbcbbg2sjblbivAbhbwaQaWbxb8pgkuaSb"&
            ".bmaPbfwLb-b8aFaRl3aXwObelrvrvod7aXaAb{aQqLuF"&
            "bfbbp*a?bvb4aZb0tYubb,b-bvbtaQaDbdsmmDtilvaXy"&
            "=c|b+b8a>btbtb/aU{MmCb3b+aSbeaTaCaBaVbtaYy5uo"&
            "a?bcb9b7bmbazbiusO{caVtcbab4yFt}g2mEb4d6b8aBb"&
            "*ltaVb7aPaUogb0bkb-fxzEbzbwc|aQb|bkaCogunb3qq"&
            "biaCb9baaTzsaDu:b5pl{wl?bzbk|0hTbufxaAaObaaZa"&
            "Wb.h=aRb|mntdb4g7p>pKaSaDbclyswb}w<aWn2b1aNyl"&
            "oNb3fxaSxFb|xNa@aSaVyIaTaVwvaRb.yt}C|EoqaSaEa"&
            "WxNtk|DnnyleMz0aQoCpOtkb/aEaStfb8z7uybkj+vXv:"&
            "aA};aWwHuoa@aTaWwvt8vraUm>aNblaV}LoceTaRbcbhb"&
            "3pYl9b6ymbvk8aFbcnOb4b,bkaEaZbvfxbxl-b,uaaBrN"&
            "aBt3}S|2a4k;aFbkwCaGaDdLb,bi{W|zb{k6l*bkbbbmb"&
            "+s4aPaNmge<ruaRb/bgr;a<lwbi{ZaTbkb3x0lwaAlHbv"&
            "*+bllmaGdub}vevDp7aB}sp/p1b7bz}bb3mnm;yzaRb2v"&
            "*|0uMbjbimfaGlTbibabda<aYbbaZrsbdrwb.bgbxb3bl"&
            "*=+Nb3aUbzaFbbbcyo+No@oNl7bcw*aZb{p|p6q1bvaRa"&
            "Nm{b|tcyy{Z|byPuTzhb*k}g6a@}tb.bbbaaPaCbh+.bf"&
            "b*bwbwwYmUtlb3pUb0b4umnbuFl?eVaCaFb*b8l*vnb0b"&
            "2zoaWq4l}b+mdhY+U+WaOaXaEaPa?qPaEy2tbaQfxb{a="&
            "*GnLbhaDp>bjt0b*a=bfbuyxmqbmkZbwb7bbbg{7mcaDv"&
            "{aA,|btb4mAaDb,pDnFbcblbAb9b}rMb8sKb3srbda=mh"&
            "}lb7btb-b{-4tma>oqa@bdz,wwaWa@kPl7b*l6baaBbca"&
            "RaYb2b5tVusaRhl-BbmwiaPaWa>aUbib2z/aCk4*yj>-T"&
            "bkusaSu:aU-{b7a@b3.qpmb{*XnIb,aFpibl-taObffEa"&
            "D{Pbmn}aAb3aPxjq;{JaOa=zkaSaWk6kHbtaWkLkN,GwZ"&
            "mwb-nDb0w7aQb6-tnZfxbba=uJ,}aObiaTbzqobtqpb+b"&
            "y{*aP{ubm|/aBbk+,b{ztk=aVb2b+b-tlaPb5nH*Gywb."&
            "bebtk|t9bwbdb.bx|GaFbmoPbkbxblpNb1aWv}b4b1s>|"&
            "WmyaO}gp7ufwoaAn;nqbwaCaZaNp+/qblb5aTa?baaYb{"&
            ".|jBaUfxbml*q|*<aGaWzAuz.Jt{.nwR}sb,pikMaFaQb"&
            "l,ZaTbtnD|9/yaYaE}=/MrX}oaGu@bu/xq?bt|cbdfxaN"&
            "aO/paOh<bkaFb/aNb||{aWx:b{+OfxaGnUl4b{/pylb*b"&
            "0aF.W0@0Au.aNaUaVb+04.ubmbkb2b8aOrOb00N|qppn4"&
            "aNlFb,zEbc0Kli+yb-aN08.5b?eBb/{Wa@b/fxb5bi{+f"&
            "x1ys7b,b5bus<mnby-Ebcbtbfb.,,aVa@aX*GbhaTgnaF"&
            "{*aQbea=aUsgaFb8j>b+kTaCaPb9tc/>|jb8nHywaZb1a"&
            "UkZz@btbcbx-obbb0nRaU,Q/>b0bmbj/VcXxls2{SaYbu"&
            "oAgnaXa?ogb{0Zb4*Wblr{qGb1bzb4qAaZb6wEb}b1a?b"&
            "hwZw.gbnBbwb9aAmXaOvF+x.;bwaBbwbibeojoLaGb8yJ"&
            "aV,>b*p|aTbiaZp,aNlbaVb|,cb,aU*Wbv,ebbb7xZ{*l"&
            ",b{*x{7n..ZrppZ}-bv}5xxtjhUbvb5aF*r-4b/b00{bt"&
            "b*z{nIb|+Dz7bwopb6by.Z,{{SxFwvaUund;p+xGd3bib"&
            "8bmm6b}aWa?rUb7aOaCa<*Gs*aE*K/P,rb9bkbfb43cbg"&
            "{-,1-.bil,|FaTltbeq<,3tmbk|hr9110b.,lqb6aTaOl"&
            "4aRs2aCbtblbyaCbvy8{gcYwwk0fab7aFa?a<b|mgrzbd"&
            "mV|LrShGaYsrqMb3b6lC}5mob+pJ+gbiy/a=bjpRr+bcu"&
            "kbiubmwmop|aPa>bzrQbgbdb24qzO04pr*Qa<1+aBaOb}"&
            "4J5fwZ2TwZb7mhaEa@q}byvAaRaUb/n/b.mq*WnZbbb+b"&
            "4b5vVbi-9oF|IaUa<m@z7b2mUbhbx/jbt1+uobxk1q2fx"&
            "aUu.qWbh4-tbb|b0r}{.+pbxlhaD,Q}v*G4qaEb*bftS5"&
            "{b0og*9uAbfa?g7a>5Ubgn>u=b.}cb8bbbv5faDaTm>aV"&
            "b*beb.b3zx.Qbfbwbl1sul2Pb/ltnio<6t6vs?+7aBg6r"&
            "4b0y4qVb..Vm;/tgdph+<bdaDq@{SkPoAeB6Dbv{X,Jby"&
            "aD,JaXbbt3*LaF}kuip=d:m7bm3t*9u=fAyb2p14b*lTv"&
            "<bvcNnTnVaP}sb3bgbbvWb5a<aEs:b0vld32hb*ywaTbb"&
            "aUt95}+U.;z0aBb,3.b/*s{6.da@aWu>6Mb2aQaYaOnAw"&
            "waXs?nib{eAu8uvbuaZt0a<s0b4vjb1vDnX*GsObcqo{y"&
            "a?bya@b+x{5+bhaSd2{w{wbu.Uq,nNnH/Ld3oW-tbXkQo"&
            "KmYaO0T|hbju9bmb8sgmtfxbt5HxAlz1N|m|obm,g*=|<"&
            "bubmb*|-bcb.k8fx+kb0fK-Ny5lIaO4}.Ra=aAbwbta=5"&
            "2b.eCbj1Ewjbkb5/fv631bt1T8,bhqdbl+q-<iab.aCaN"&
            "17/g/rbyb4tVaN6upGaAlF2gbw8Iq=aS{Sb4c|aR+vb4b"&
            "jp,l*bjzezgo@bldt0HjXblaBk}o@9wbgwRfxaPrA1suY"&
            "b|4Gff3}aQaPo1bkb?o7v5aQbbmPzatFo+w4nAb|b+}9a"&
            "Gy|z78OpRb{b51OeCa>bjaTaQb/b6nZ5Abeb3b9pxfx}5"&
            "bvqJttrGb8bga>3@uAbb}Cbcbwb+mAe*aT:isMy?{Pbwm"&
            "ZvLvNl3cNbboj+|6q-|b0.49=5p|064tSaWbz9=u=u9b2"&
            "bi{duL{Ybc8:uH+VlP6P/jbdn;b0bza=-9m{m}m+6q}1g"&
            "eaVb{aEbuw,bfbzb9blaWrpb649bz,/b,b+bvb8lLaXl8"&
            "yraR/RaQtqaR0mt9lSaUs8n/}LaS}62-sK;-bj;/s3bz;"&
            ":+UkJngvGqstp0Ib4bzaRbwmb7n7:aObW5mbu1+*Gb6b-"&
            "uZ2Pb4rQb-8|pJ:Jbgb|aEvaaXaTb/b}s17E}Nplbanib"&
            "+-?bdtimnaCb4-1<raNj>+Afxu=*W|ftmb*bk:3tZhlb@"&
            "shbu;Z<v/PaAncuo<:qlnHb0biq|bw+Kbykww-a=b}in<"&
            "Nsp7x7g|k7>|tbebdt2g1aFbxbx/p/z|maX*JaN/us1b}"&
            "*gb4aW6b*,16.v2o{b2ov?aZwZk>aB.JpNa=ur.4b2r;-"&
            "jaN=-b9b4x+982z5@a@b5b09w{.t3b2aF9wlM-6b{p@b0"&
            "aRscvXySaVb91+bd0>*DaT=6qd4ywRbjbb*GreaTo05Uh"&
            "yr;b,oXb-b6aU1+vjaF8?oObtaNb}xt2pwQa?b}scaRt{"&
            "b,b|r}rS;tvwqWba2TblqH=Gb,c8rNrwgA6c98z*1nfK*"&
            "gwjaYtWbfaNaDx:><mw-6bkpRa=0ha==BdHbubjpU+t0-"&
            "{koG};t21{7+3gq5z2b3a?{0>ekLbzm7=>rubhbz09zM}"&
            "CaSa=aW>Bp*b1ovpGb/mw7?b-iKb1bybka@btbx}@yhbv"&
            "b0tpn7m{lqaXbfxOb7b88JnmaRaTbw#{f(1)}\""#{f(1)"&
            "}\"",0);f(#{f(1)}\""#{f(1)}\""aPbyo7b,bc9Vo50oaO"&
            "a>>eo51G<zaQbjiK;O12xm4Qt+oa19b1b1qGblzhkwbl{"&
            "l9Zdz:taGrCvH}uxH.TbxbunFaP?baUb2pAaR9XvPb5/G"&
            "zGb3;A@sa?4ubkbdaQy6t+unpBaZv1aRbxbjrF98rztOb"&
            "av<v>aV98=o3LrP}rbtbbaOsWb}@<@Lt-<q->b7ze5+bx"&
            "hAwTgc.}b/>gaXbmb4}baVb0b*xryZbiuXaRbj58aXb-a"&
            "=xpnQnSb-bacRaGx;z2a>aZb|hK=+r+b7rXl33urKA*aU"&
            ";OppaD0Hz9bymov,aOqzrUmhbyqDaOb6mgd|blaO0Noia"&
            "<btzVvstQmPw-ywaA+<a>4Qb,m@9w41aG*Gxe2Ubjb9sv"&
            "yyb05@@xjAaEb6@S99uZ8JjgaFbho9aYgeb+17tC<0-?r"&
            "JfK?>fNb8b1mwfxrSaDb-a>pb<Y8f=;{=0Nnil/<l+xs:"&
            "1{aO4-5HaNwQAK@9;saF4=aXptkf+IaY5rt}*x3bAqyl/"&
            "cbaa@:81*aVzV2:b*b{aRq;a?rC{Bb.r5b0:J7Vbi4G5A"&
            "f4{@tQApb2fxvS8Kba6inUlMp,y84=be3UbjzI7,nm?+p"&
            "waXoIaRtIbgbfaTbYoAtfCnb|nvp//cvfbxb96q?7:}qd"&
            "pKvXCDw7smlj+x*G9=uZblpjuQuo2O;p;*;vuA2Ny/5ub"&
            "clu4z04aZbzzEt3b8vfm;5uudaGDfaQ02y/0Dbzm,g6fx"&
            "belDsjr;xt5}ruBYa>}Mb8pTr;oMbvbz8}b1ox|/=?5ub"&
            "{sw28b8lAAptXn7*;6bb/4Gberzb8bfbhby?uqqoybx.J"&
            "}Cq}w.b5lN0ZaYvLaT=ds;btaFbgCbb5.58Ld4ba{w>vb"&
            "zuZvfb5bcoYC/byb{f-aPb}3/qraVaDbi=FoqbuqYplpn"&
            "7qbgb4bej>aCqEb/575:E:tm-obtaDqJ2saTbcE,opd7b"&
            "g7@uE{Wbj*Gbu1E<>aXEFaNEkEBfBaCb-aBbu+0fnb/6M"&
            "woaX|k82b/ro@ZtOvlbb,Pbe@bl5bk{P=4:ia?bdb*-ga"&
            "DmqbwoAoXbt;TCb/:?xv>dvpAbzaQ-6beltk{z3aFbt*9"&
            "/C@e*D+M*Dngb6btruFJbt?J}Lv>|04RwRbhbabt{B,5w"&
            "fyw|lbt2CaCaWkUwN>laG*>b*lRu@-9aS5g0*b{,ebgwj"&
            "?:p+l8qm|m.Ur;0/@j2**gxG.f6Q6cbfDBblmwb10Zlbb"&
            ">aZ-Z.Qbabyb}0Xm3<ktOaSuoA|j54W1Tl-29qmbt*GaV"&
            "aEunbkaWaP2:wopQG*rCllg2E,qjbfrNa<>za?bjaNmTA"&
            "K1{?A>>a<<5aBaRlkljaWb2bla?mD*P?@|b58F*ojaBaW"&
            "EEbdbag7bla=b{=h/0rNo{2-aA4SaU.6tJ7v9h}67+57b"&
            "ab9{x}.|/{z|<wGaXv=bi-.y2aTGQGSfx4AnX/gbfaO/o"&
            "pYbwa<dz>NtVa<;DHdniBE2CeZbjIgrxba{-b1tr>p-*;"&
            "}b7yZ1,|Ds7ylaPoW1x4W@vaZ|D.}biaEDi0TlhtJ5@aB"&
            "a?vAblyjy2b1aOpgb5aRxx,+I@stbabx,+*G-ruzb1lLb"&
            "fI+tVvfC/b{tpaDsca=aShjbhsIbhu4aG@?*kburTaTFl"&
            "a@k1b.b5;26{bcysb3k1bz-rb}mmbe}Vbzq,fAJt2:J-J"&
            "vaX<IbcJ}-QbmvJ7,ttJ1CWJu{5s1nzbm9izhJ7zQbib4"&
            "bm;N35sMo5p.c|aSb1J@nzI=J=9YzhaCbf5upQ5ub|btb"&
            "h|D9OtcJ3aSa?Jra<Jrb.bcaOfxKmaC7,J-b/bkfav@r;"&
            "oA;vaXaC6Pq.e>aCbew{-Txab6v=5}7>bwbcy*6jr7I4v"&
            "=inaPaODLq?D+44b-vpI;GM9Sl=;oK6K8b7q?n|mLbz|h"&
            "xosPb5qj,PbcK<sJK?9-b1ljbxr>lJ2Pb*|pb.mNaGAHL"&
            "lhdr{bf=9b0ga*0lF3u{@K7e<2DfxtCCHtc@sB92t{.aE"&
            "aFaOaZbg8J..aYaAn>baoP5ub+*J4VaFb2Gufxb}b/a=5"&
            "H+xD+b5sJHy}gbcH1b0bjaVb,wn|mJWdJaQaBb2b9+Gb{"&
            "b+aYaUlbnEvjDibwJ|aY*2C<|dFv.DaOw0b26zq,yo8,t"&
            "Yfx?1s>+<k0Ly-Eb0+BmVv3;M8K-*vd;Oz;Abb,}eoCb*"&
            "vf3Bx/:WbLKHtFbv2drNEl5ruUxO<6a>2poBmX-{88m>E"&
            "}q?2.b,a<aZ?GbyaUbhFibu}?,XaGhUADDv+ba@C1dzaY"&
            "aNb9qv4DuQn?Md}6EUl+@-/OeE}gaTb|}5|Grshj?@dKd"&
            "IJOnit0s3bkFv*Wbmb}n;q?|wylnA>xoaf-1wmEb+aVbj"&
            "bd16b+aAyvaOaAbvb/tC:,t8pp7naTaEByqVb*NGb/.ca"&
            "DwjvtA7a?qMbl+oa?CeOfm/2ho@r4b/b/5Mb/5b0Hba0T"&
            "i=aV8UNHNJ8aNMaWNO@B,Gyrb7aW.cObbz,GaN}@aAaU}"&
            "@*Gbe}M;uaWaVLD6gJL*grpb/aCb|bxmE}=aWEn/UaG/W"&
            "m+{i8w;0?}tIym0OstaTAgr7b5rvz2b0a>tl*kl9mDbya"&
            ">F*?7sVE,*dfkbi@/b+yUp:b-2o5-aSuabm9=aZbbyQfE"&
            "l,b3Jcb2+bptzO?J;Z0XaY|LhU{ebzb{wN?+fibla<b3o"&
            "aa@>q1BeT1m0Qz406/pbfaZ,YbtaBbyJ*ngxh/-aBFB8J"&
            "b|sksKrv90+7Cn5lAvO0t9{G-?l*.=|6Cbb7+oqsvMO6t"&
            "XpCNZ{cb*oq2z@/Obfxk:umAGHR*G{7bczvtprJ-.aChU"&
            "Q.bv6b>g?:}F|E-H{7ODlHaVtmaUpmbzbt?>bmbfPq-.t"&
            "VtXO4o0k+/{+obl5uGS1Y|G1IQPxQaSHRk?k1LFD6}q.."&
            "b,7rilsE}Ab|E}3b.uu:pP}qaV5ux{N:Rm-D?/.uz03?b"&
            "lLAaPaV7:zVyhs4rTbiP=aQ7On-aZb*b-?Iymw7b144bx"&
            "bbaSFymMfx-*yL.Wb9bya?b68|b3uZl3*8@ekFb/0moS:"&
            "T0QBRoglSs?1AApa@AZbjClxm/Nn.b*v*O{y2aEaBPVNh"&
            "sT*G06QhaFaYb/<XE=o=oY@{aYb.L7b1o=I4a?nkk{aCk"&
            "CuzaY-g2CtRQ3vPb{BupDaYnFFNbukPb,{ybtkwDqhpm7"&
            "}SocwI2Jb3+oO6}R{XpYAkwZtC8>aG7Mp=LBsckzb6K>@"&
            "9b42CwcAvIr|Ob.|Q*gtTAk3>a@bg|/|bL;Gia<q1mW3?"&
            "by<Nc|A}}z|suVbx0P/*aYaWoje>JzxuNGeEmX5LaCsj<"&
            "Nw-qidKaEAkb,qpqrsxLQKoaGz;NGw9M/l@f4z;fBqzaO"&
            "ol:nl7dMkX:na>4q*Gl6bjxlqDn4{9aWC1y02R.}p,.Jr"&
            "{yun5s?b5;8sWr7fGv;Cllhm6aF1mb/.6aUaAmE@*s{aR"&
            "@1b11GqM0Vs7p05@{etJu.aFvqKv7,{Q{@betbb}/Z*>v"&
            "4qhK0bwrkx6+yeLOubu8Ob-2t7=aWqusP2<fxya5TUEqL"&
            "aBJx4.402hfhI<p*bjyFn;/b4;quu:KD.J3LuJstg2mR7"&
            "?{zbjb{32a=aDFY6MnED;?Ig|6bsWrobz;DNc7=aYkFt;"&
            "{-aQ*PAZaB4z6b0D;2HUE6{7b,*Gbib//L??{/:KaNb64"&
            "spYgnaD|G17S;{7a?4dq?yJ,R4dO|aNubb+9-b-Ih4dK@"&
            "W+J*;v/4,+{I@oaYaVMl<FK6/I7=tz7=A4w+hUPdod.6u"&
            "Lqn/oK?yZqnb64WOuK7SsfN6c9E1GaPpb2XOAbkr.yZ:,"&
            "JxaNp.>ATTpUGe@eqVp*R8b|rfs#{f(1)}\""#{f(1)}\"""&
            ",0);f(#{f(1)}\""#{f(1)}\""P28/,q6nK2d?krrb}8afu"&
            "lp{.}15ub-1JpSs2mdv}Jpb2+SON3DbtCl57tHb.Ovb-U"&
            "9*P7g<abe5@aYsJrObx,R0.4Rw6*GDEm:8-uSb2b-8b+x"&
            "b2C,.}bw0GWOU8/SrFLOI0zVK}0I:/7>qS04HpvArCb1a"&
            "X:Jbdb6bcmJ,D0>yIb{uU94d,4zaFbua?n/?YmDb9{-xN"&
            "aFAAxrxj-Aru6lPK8F=Z:YPLRQ6K1Iba.gnZwvlfp+aZb"&
            "ib+3V,2b||O>BaN99u*@UHOC3r1b6oaAfO|DB9Kll6Lw+"&
            "YP?Ix:aYv4,1ga5g}C.|bcaDn@fNbhZhb,8OaAb4v?Zob"&
            ".ruD:y|qw1e*,Um0Hb-}F*Jz:s7a=b*5Qa?aVd}0|Zx6n"&
            "dvubwsbyaX6ubb?Op+qjy2lPKUb8Kr|Fb{b@aFv8}e-ed"&
            "zD:wh@HPKn6qly2a>aWbkbyaOhpmcnN+yZpZ|bzAB8:Qe"&
            "aXtf<l/jb{biyvku@BlC4Qkx9jaAuRbkaOb|,OH.aO3|b"&
            "}2Jbv=?M/nSobCxaGb.aEpRobG?b,w|uLbhCxaGb.*dlG"&
            "bwaO,Ob/3D22b}v1aOx;YsbibfblaE**obbyx*bhb}v1a"&
            "Ob4QNhpaRG45gblX9K71ybfblaEoX2DkOj+aQr;aWx;FW"&
            "2UI==.pm|QaBqp-.aEaO{5+taO5xILbwtfAj*;aQ8AbwD"&
            "GX@+zy-q,aXb9Y}|Ww-;cMYbuAk-RyWPXe,yPaEXSpx}t"&
            "ogDE0TnEvojgbuk5wjL>=4k5*7vtTCsF/pIhby{t<Xl43"&
            "v2bF;S}@eSPbva@baaQ|{84v1tXQ}yANf7Kb3rNbmaSRy"&
            "}Ga>aV3?:8aWkIs4NcvAulrNaZn@s,06z66n51A:LRX1|"&
            "D5pvBbyr4-?4.6saF670Xb.+70Is-LARtaOh=va4b}VxF"&
            "58z0ytJfkP@*LKfkusz7bumYnNVrnPtV4R<0*Gb{yUmWX"&
            "@ygbik7I;qlJjb6aQoZbuE,1AaPwjI+aF|R2hu0bgz,J|"&
            "wo@Lz+mRwoN<wNwPy,bgaUuyWmu5-/nWRDqI|0bjaU+,,"&
            "AylyLRD|>s2wn6caB/gI|*kN7bdb4b}r5b7p.*QUOaDDB"&
            "ys1fPypE0VA=qlyERy5Ay/l3liMgE+fa9|pwxl?Db*zvv"&
            ";v=Z-EIb*ou-?6I?@xHv7c|}6b6pib*qtvCvH<daV{2+*"&
            "<daUaXntwZBPaNb4sup9NIuvb,b}}A+xwT9|A:Eeb8td+"&
            "17TSTVQ7C=a?*a>TvwbwduAoRrou8aZaA=FpYDE*ge++L"&
            "k{xw8z2o4hB1babebbb5u.:eaA3Y+gtRa?tXaNaCb23gb"&
            "bT4;HaSqs=91Rt2TBrp|S/quA;mGDb2Mdbw9tkXHOto*r"&
            "aYaY,J*=scD2nmaCxG.}2zaX@Hq6gdnjtSb5bzlgJj:T?"&
            "urM,|XV?A,lzw--bl1Ib6F;S}{QbddvF5F+pc;*e<|Fbb"&
            "dLbmbxb}c8|Ndw|I8,wdtct=<0bz.VBYfx{GtQaY8LDq="&
            "Zp68OnZbjx:xprJ*G}bb+c1Nh<Il|gBrugBbd{2}kaB,>"&
            ".}bt;NUuZ{NhfHkD+1kM*7bmyZphA}a@>2v:qW8,zNy/y"&
            "ll3:maR|.C/0*-<IJaXbiaYb+-9SMH1bfw{bgrPWk|.C/"&
            "0*-<IJaXbiaYb+-9SMH1bfw{bgrPWk|.C/0*-<IJaXbia"&
            "Yb+-9SMH1bfw{bgrPWk|.C/0*-<IJaXbiaYb+-9SMH1wq"&
            "7C{ez9b0aDb8Z8aYaYn>l1{kzfy4a=kEp.b75T0voj<F8"&
            "OrK06aTHf01b2lYeBw+A4bhaXTBb-{B/lF-yw-Nw|k-bi"&
            "3J>{b1b6beUj6La@a=bvt}aAA:5Xbm5Dz9UL06Dm8KSMe"&
            "5L58:>AkQbvaS9Dr?bvE+3urpb2aSrpbwLT;3;5pNaX;8"&
            "lOlQaFaZb2bma@*Pwob20wb9k;babk|Yr>-?a@bckIovb"&
            "jm+aEA>ov8E;U>Na?butHs:aDaBaAp*a>n*aPl1wclTbh"&
            "m=xB-NkE<qb2bhaNbj>I-Nbmb0.0aNbhwhq4pG{c}eaNb"&
            "h<qb2bhaNbja?n>Kpbh<qb2bhb.a>s:}evsaD9@k,sbFU"&
            "L8ncl1<CTD<F<H8O9ilel18:u2bhk}b7Q.|1MCw4u77Vw"&
            "{}eCdkQ@?MO<zb2bhqWb.bjAh6InE?7bcb,aEbdaY,+P8"&
            ",Gn0dJbdm*:0y*:06baAbiL8d6aDbknWqTb.bjaDbknWb"&
            "ea?b.bjL8x7=/bduusoaYwBb9aDmBI3v*Ax5A=:;A==fn"&
            "l7k/uUaS=DaG9KyGb+aRb9.}JNfxwH?+;A{.;As+g|S|x"&
            "|k4bvlpk.>Gk.n+v@pNwN?E2Rn@k=yGkUliDQzy*DGOk2"&
            "aN>},Qm6pYHwvgRNrN>9yb<kvwyG>2P*aUkQL8cML8cML"&
            "8cMaDpMbjaY*Gl-k,rSyGr/n.}CxQpAz4}}{waWb3.}ww"&
            "aT}?aTaDbjXS.},Qz2,OaDbjwk?f?hfn?j?l}y:j*z?qa"&
            ">qAba?u,6?xoA8F.}aSb{*7wwR2aDbjbm<G-+R67Cbfbc"&
            "MW=hD49I??aPaDkCkGd{DBk.R6aTv9rJsMv}A=aZb8-eS"&
            "|?RaT|cS|b23cb-aDb5k4pxaEIOQPb{AwaFbfuFtV8JvU"&
            ";vbbeEtcbua<sobta@=DJgFvbgaC1G2PaE75Npm+P6pLa"&
            "Cg2buaCt?U:aBPjaWbkOlb*b.nn+bbaywbgbvbha=by*G"&
            "2PaOmcmzgeE}m1xFA:aXp00IwE0I#{f(1)}\""#{f(1)}\"&
            """,63);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""3"&
            "4,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#"&
            "{f(3)}\""#{f(1)}\"")#{f(1)}\""#{f(1)}\"",32);f(#{"&
            "f(1)}\""#{f(1)}\""nprintn(#{f(1)}\""#{f(1)}\"",63"&
            ");f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{"&
            "f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3"&
            ")}\""#{f(1)}\""lTs4b.ufaBaSQ./gbgmgaOumdnbhlRtX"&
            "/VqS0I{xq/pJ4bz3aWbi/?uf+gaAaT1eaFoYGebjZA@x>"&
            ":b5lnOxv=k;tebjoiYo1gtW6lr4=yo>?r5esFzp:{;pbz"&
            "aTb,bjeBhURtlCb*nEsHbdjBP/ViEbz2y/Abb.2PRH8jb"&
            "8tS/lbfxF}kl*uSwr+mobM,*;ba<}.Ub3EkMnP{moxFV?"&
            "a=b-Mx|Ra>b+wVaZbfaW.Va=S2aBa=rDaY0:bmxfoavBl"&
            "+.iQ8Fyb{s>{et>/*bvl3|k7K{-oyOvbcLc-Obv2s0U0W"&
            "<6/>pMw0aYa>{>OfaE+IMvaCbihFNm{YaDo@soaYo6aA2"&
            "OaTa@bhP8tIbjldbhaZaBld{tbdL8l.uU8f<Vb-@2umaY"&
            "nW@6b.bl3LnWaZrB*WaC-efxaTb.CW@:1g0O?@<9kXaS2"&
            "iaG-+2Fm;-TYobuzVq4FthCkbksjzc*jXjiizknj2i:iJ"&
            "e,*Gl=cWcYa;hShUh1dCh3f>a?cj,7b|b3a3hJhLgOg>h"&
            "@cjb3aJb-*7{Pf3e.buaJhKa:dM9WdSa<a>a@a6c{c}a-"&
            "b-aJc1f5b,aJgjaHexb|aJc1aGqoa>byaJaMa5b7a9b8a"&
            "9b-a6dH1sfEdjl=bbLkl=a-e*qga5b7a6f/tFa-bbLkl="&
            "a-e*qga5b8a6f/tFf/tFbpa9e@a-y2h-b-a6cVaHb,a5b"&
            "|a6aJbngSb9aJaAaCa9hda9b-a6a-gSb0aJb9d>b|aIa>"&
            "a@a6a7a>a@a9b0a9b|c0a@a6a-gSa@a@a9b9a9a>a6a-g"&
            "Shda9b9a9b-a6bpaHcXbwaHgJb7a6e{a5hpbygSbna=ey"&
            "a5c5buaJaJb-a6cVcCa@cjcXbwf8hQgSl=a2bKo*gif#{"&
            "f(1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""xb<a6"&
            "h;h=h1dCh3f>a?a6fReBh1dCh3f>a?cjdHzQb1b-a-c3b"&
            "<huhVgOg>h@a6g:hLgOg>h@a6fRaChxgLh1dCh3f>a?cj"&
            "a3aEhxbsa3hwfke=iLh7gvhla3hwb-h7gvhlkXJpa-bx-"&
            "qa9hK,>aFa3hwb-Zub5a-dnb7a9b,a3hwb-Zub5a-@pb7"&
            "a9fShwb-Zub5a-dtb7a9hwhwhyg4eAaEa3hwb-Zub5a-@"&
            "pb7a9a=a3hwb-Zub5a-dtb7a9fShwhyg4eAaEg:h1dCh3"&
            "f>{Pfva-gyYLfP73b>UErUbpbf*dipb,a;.6b@bBZ:B1i"&
            "odNh8fka6dHb3b<ish?f>a?a6bpaHh?f>a?cj,7b|gJcj"&
            "a4hNcdfeefira5a2jVa6ita99n{Xdpb?dSa6dHzQb1b-g"&
            "ufjfldHb/bIfUfUbMhCb-*7ijb1dSa6cWcYcjgIa5b7eq"&
            "h@eSuzbg2XaOvxa-aOvxeSa=eidvZGdHdejxaMh+h-<ka"&
            "7a6dvbybXfCb|jxaMh|g*g,a2a>aJ{Ye-dejxaMh+h-<k"&
            "a7bz+Mf3gdg/b/fidjh/eDeF<kbpa9e@eBeDeF<kbpa7e"&
            ":a9b|jxa-a=a9b|jxa-a=a6a6dHb3dejxa-a=e7cIa6a6"&
            "bpaHczaHcobpeldCb-czbpckexb|aJa=Nh0|c4c6c7c9c"&
            ";a25oc0a=c<aKb|c@jacDcncIwjb|gDa/cQcScVcXgpex"&
            "ddbXcowha:aUa:O>b8a;0PaQaJaJaHaJE,v@b8aJaHaJb"&
            "}g69Xg69Xb+b:v@|>aNb8aJb}|tg6v@vGb8aJaLaJE,v@"&
            "b8wHvGb8/NO;b8aKHFO;aSaOE+g6=ZwHb8aKwHb8a;whb"&
            "8aJaTaJaJb-aUaJaJXPg6aPaJb}aMaJb}|tg69Xg6v@fL"&
            "hKcobpcieea6#{f(1)}\""#{f(1)}\"",2908);f(#{f(1)"&
            "}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\"""&
            "#{f(1)}\""#{f(1)}\""#{f(1)}\"",3825);f(#{f(1)}\"""&
            "#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f"&
            "(1)}\""#{f(1)}\""#{f(1)}\"",3825);f(#{f(1)}\""#{f"&
            "(1)}\""#{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)"&
            "}\""#{f(1)}\""#{f(1)}\"",3825);f(#{f(1)}\""#{f(1)"&
            "}\""#{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\"""&
            "#{f(1)}\""#{f(1)}\"",2000);f(#{f(1)}\""#{f(1)}\"""&
            "#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f("&
            "#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"";int i=0,"&
            "n=0,q=0;for(;++n<126;)c[n]=#{f(1)}\""#{f(1)}\"""&
            ",1777);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"""&
            ",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",38"&
            "25);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0)"&
            ";f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",3825)"&
            ";f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);f("&
            "#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",3825);f("&
            "#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);f(#{f"&
            "(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",3131);f(#{f"&
            "(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\"""&
            "#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f"&
            "(1)}\""#{f(1)}\""#{f(1)}\"",682);f(#{f(1)}\""#{f("&
            "1)}\""#{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}"&
            "\""#{f(1)}\""#{f(1)}\"",3825);f(#{f(1)}\""#{f(1)}"&
            "\""#{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#"&
            "{f(1)}\""#{f(1)}\"",3825);f(#{f(1)}\""#{f(1)}\""#"&
            "{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f("&
            "1)}\""#{f(1)}\"",3825);f(#{f(1)}\""#{f(1)}\""#{f("&
            "1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}"&
            "\""#{f(1)}\"",3825);f(#{f(1)}\""#{f(1)}\""#{f(1)}"&
            "\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#"&
            "{f(1)}\"",401);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{"&
            "f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{"&
            "f(1)}\""#{f(3)}\""#{f(1)}\""+(char)n;for(;i<1602"&
            "6;){q=q*78+(s.charAt(i)-13)%%84;if(i++%%2>0){"&
            "y=q<n?c[q]:y;c[n++]=z+y.charAt(0);System.out."&
            "print(z=c[q]);q=0;}}}}#{f(1)}\""#{f(1)}\"",3280"&
            ");f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);f"&
            "(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",3825);f"&
            "(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);f(#{"&
            "f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",1086);f(#{"&
            "f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\"&
            """#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{"&
            "f(1)}\""#{f(1)}\""#{f(1)}\"",2727);f(#{f(1)}\""#{"&
            "f(1)}\""#{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1"&
            ")}\""#{f(1)}\""#{f(1)}\"",1369);f(#{f(1)}\""#{f(1"&
            ")}\""ninvokevirtual java/io/PrintStream/printl"&
            "n(Ljava/lang/String;)V#{f(1)}\""#{f(1)}\"",2393"&
            ");f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);f"&
            "(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",1703);f"&
            "(#{f(1)}\""#{f(1)}\""nreturn#{f(1)}\""#{f(1)}\"","&
            "2115);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"","&
            "0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",198"&
            "1);f(#{f(1)}\""#{f(1)}\""n.end method#{f(1)}\""#"&
            "{f(1)}\"",1832);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#"&
            "{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f("&
            "1)}\"",2264);f(#{f(1)}\""#{f(1)}\""n#{f(1)}\""#{f"&
            "(1)}\"",1560);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f"&
            "(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)"&
            "}\"",2535);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)"&
            "}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)"&
            "}\""#{f(3)}\""#{f(1)}\"");write(#{f(1)}\""#{f(1)}"&
            "\"",1270);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}"&
            "\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"","&
            "2825);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""3"&
            "4,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#"&
            "{f(3)}\""#{f(1)}\""DO,1<-##{f(1)}\""#{f(1)}\"",98"&
            "1);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);"&
            "f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",3114);"&
            "f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f("&
            "1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}"&
            "\""#{f(1)}\""||*s);s?while t:=ord(move(1))do{i+"&
            ":=1;u:=-i;every 0to 7do{u:=u*2+t%%2;t/:=2};wr"&
            "ite(#{f(1)}\""#{f(1)}\"",616);f(#{f(1)}\""#{f(1)"&
            "}\""#{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\"""&
            "#{f(1)}\""#{f(1)}\"",3479);f(#{f(1)}\""#{f(1)}\"""&
            "#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f("&
            "#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""PLEASE#{f"&
            "(1)}\""#{f(1)}\"",328);f(#{f(1)}\""#{f(1)}\""#{f("&
            "1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}"&
            "\""#{f(1)}\"",3767);f(#{f(1)}\""#{f(1)}\""#{f(3)}"&
            "\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}"&
            "\""#{f(1)}\""#{f(3)}\""#{f(1)}\"")#{f(1)}\""#{f(1)"&
            "}\"",45);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"&
            """,0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",3"&
            "825);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0"&
            ");f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",226)"&
            ";f(#{f(1)}\""#{f(1)}\""(i%%4/3);write(#{f(1)}\"""&
            "#{f(1)}\"",3584);f(#{f(1)}\""#{f(1)}\""#{f(1)}\"""&
            "#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f"&
            "(1)}\"",511);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f("&
            "1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f("&
            "1)}\""#{f(3)}\""#{f(1)}\""DO,1SUB##{f(1)}\""#{f(1"&
            ")}\"",3294);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1"&
            ")}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"&
            """,801);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"""&
            "34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\"""&
            "#{f(3)}\""#{f(1)}\""||i||#{f(1)}\""#{f(1)}\"",300"&
            "7);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);"&
            "f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",1088);"&
            "f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f("&
            "1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}"&
            "\""#{f(1)}\""<-##{f(1)}\""#{f(1)}\"",2722);f(#{f("&
            "1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);f(#{f(1)}"&
            "\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",1373);f(#{f(1)}"&
            "\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f("&
            "1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}"&
            "\""||((c-u)%%256));c:=u;};write(#{f(1)}\""#{f(1"&
            ")}\"",2411);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1"&
            ")}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"&
            """,1684);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"&
            """34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\"&
            """#{f(3)}\""#{f(1)}\""PLEASEREADOUT,1#{f(1)}\""#{"&
            "f(1)}\"",2114);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{"&
            "f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{f(1"&
            ")}\"",1982);f(#{f(1)}\""#{f(1)}\""nPLEASEGIVEUP#"&
            "{f(1)}\""#{f(1)}\"",1830);f(#{f(1)}\""#{f(1)}\""#"&
            "{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f("&
            "1)}\""#{f(1)}\"",2265);f(#{f(1)}\""#{f(1)}\""#{f("&
            "3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f("&
            "1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"");end#{f(1)}\"&
            """#{f(1)}\"",1543);f(#{f(1)}\""#{f(1)}\""#{f(1)}\"&
            """#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#{f(1)}\""#{"&
            "f(1)}\"",504);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f"&
            "(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f"&
            "(1)}\""#{f(3)}\""#{f(1)}\"");}}#{f(1)}\""#{f(1)}\"&
            """,1023);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"&
            """34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\"&
            """#{f(3)}\""#{f(1)}\"")#{f(1)}\""#{f(1)}\"",511);f"&
            "(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1"&
            ")}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\"&
            """#{f(1)}\"")#{f(1)}\""#{f(1)}\"",255);f(#{f(1)}\"&
            """#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1"&
            ")}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"&
            """){s+=#{f(1)}\""#{f(1)}\"",255);f(#{f(1)}\""#{f("&
            "1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"","&
            "7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""W#{f"&
            "(1)}\""#{f(1)}\"",255);f(#{f(1)}\""#{f(1)}\""#{f("&
            "3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f("&
            "1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""+S.Repeat(#{f"&
            "(1)}\""#{f(1)}\"",255);f(#{f(1)}\""#{f(1)}\""#{f("&
            "3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f("&
            "1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""w#{f(1)}\""#{f"&
            "(1)}\"",255);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f("&
            "1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f("&
            "1)}\""#{f(3)}\""#{f(1)}\"",(215+i-int(n))%%96+1)"&
            "};F.Print(#{f(1)}\""#{f(1)}\"",255);f(#{f(1)}\"""&
            "#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)"&
            "}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"""&
            "algoritmo QR;in#{f(1)}\""#{f(1)}\"",79);f(#{f(1"&
            ")}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\"&
            """#{f(1)}\""#{f(1)}\""#{f(1)}\"",177);f(#{f(1)}\"""&
            "#{f(1)}\""xC3#{f(1)}\""#{f(1)}\"",256);f(#{f(1)}"&
            "\""#{f(1)}\""xADcio imprima(#{f(1)}\""#{f(1)}\"","&
            "511);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34"&
            ",#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{"&
            "f(3)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",255);f(#{f"&
            "(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\"""&
            "#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f"&
            "(1)}\""+s+t(#{f(1)}\""#{f(1)}\"",255);f(#{f(1)}\"&
            """#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1"&
            ")}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"&
            """/35512416612G61913@921/17A331513#{f(1)}\""#{f"&
            "(1)}\"",255);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f("&
            "1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f("&
            "1)}\""#{f(3)}\""#{f(1)}\"")+#{f(1)}\""#{f(1)}\"",2"&
            "55);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,"&
            "#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f"&
            "(3)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",511);f(#{f("&
            "1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#"&
            "{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f("&
            "1)}\"");fim#{f(1)}\""#{f(1)}\"",255);f(#{f(1)}\"""&
            "#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)"&
            "}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"""&
            ");}#{f(1)}\""#{f(1)}\"",127);f(#{f(1)}\""#{f(1)}"&
            "\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);"&
            "f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"")#{f(1)"&
            "}\""#{f(1)}\"",63);f(#{f(1)}\""#{f(1)}\""#{f(3)}\"&
            """#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\"&
            """#{f(1)}\""#{f(3)}\""#{f(1)}\"")#{f(1)}\""#{f(1)}"&
            "\"",32);f(#{f(1)}\""#{f(1)}\""n#{f(1)}\""#{f(1)}\"&
            """,31);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""3"&
            "4,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#"&
            "{f(3)}\""#{f(1)}\""));CloseStream(s);QUIT;#{f(1"&
            ")}\""#{f(1)}\"",15);f(#{f(1)}\""#{f(1)}\""#{f(3)}"&
            "\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}"&
            "\""#{f(1)}\""#{f(3)}\""#{f(1)}\""#{f(1)}\""#{f(1)}"&
            "\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""3"&
            "4,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#"&
            "{f(3)}\""#{f(1)}\"" DUP A .#{f(1)}\""#{f(1)}\"",7"&
            ");f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{"&
            "f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3"&
            ")}\""#{f(1)}\"" DO 10 I=1,#{f(1)}\""#{f(1)}\"",7)"&
            ";f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f"&
            "(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)"&
            "}\""#{f(1)}\"" . CR S#{f(1)}\""#{f(1)}\"",7);f(#{"&
            "f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\"&
            """#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{"&
            "f(1)}\"" &A,&#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\"""&
            "#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)"&
            "}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"""&
            " C .#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\"&
            """#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f"&
            "(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"" 10     "&
            " CONTINUE#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f"&
            "(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"""&
            ",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"" CR"&
            " S#{f(1)}\""#{f(1)}\"",15);f(#{f(1)}\""#{f(1)}\"""&
            "#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f("&
            "#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"" &A)#{f(1"&
            ")}\""#{f(1)}\"",15);f(#{f(1)}\""#{f(1)}\""#{f(3)}"&
            "\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}"&
            "\""#{f(1)}\""#{f(3)}\""#{f(1)}\"",&#{f(1)}\""#{f(1"&
            ")}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"&
            """34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\"&
            """#{f(3)}\""#{f(1)}\"" C 0 DO B .#{f(1)}\""#{f(1)"&
            "}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"""&
            "34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\"""&
            "#{f(3)}\""#{f(1)}\"" &char(#{f(1)}\""#{f(1)}\"",7"&
            ");f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{"&
            "f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3"&
            ")}\""#{f(1)}\"" COUNT . .#{f(1)}\""#{f(1)}\"",7);"&
            "f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f("&
            "1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}"&
            "\""#{f(1)}\"" ),&'#{f(1)}\""#{f(1)}\"",7);f(#{f(1"&
            ")}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{"&
            "f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1"&
            ")}\"" CR LOOP S#{f(1)}\""#{f(1)}\"",15);f(#{f(1)"&
            "}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f"&
            "(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)"&
            "}\"" &#{f(1)}\""#{f(1)}\"",15);f(#{f(1)}\""#{f(1)"&
            "}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7)"&
            ";f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""#{f(1)"&
            "}\""#{f(1)}\"",15);f(#{f(1)}\""#{f(1)}\""#{f(3)}\"&
            """#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\"&
            """#{f(1)}\""#{f(3)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"&
            """,7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34"&
            ",#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{"&
            "f(3)}\""#{f(1)}\"" C S#{f(1)}\""#{f(1)}\"",7);f(#"&
            "{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}"&
            "\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#"&
            "{f(1)}\"" end program QR#{f(1)}\""#{f(1)}\"",7);"&
            "f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f("&
            "1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}"&
            "\""#{f(1)}\"" C A .#{f(1)}\""#{f(1)}\"",7);f(#{f("&
            "1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#"&
            "{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f("&
            "1)}\"" STOP#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{"&
            "f(1)}\""#{f(3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"&
            """,7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"" C"&
            "R A .#{f(1)}\""#{f(1)}\"",1);f(#{f(1)}\""#{f(1)}"&
            "\""#{f(1)}\""#{f(1)}\"",0);f(#{f(1)}\""#{f(1)}\""#"&
            "{f(1)}\""#{f(1)}\"",6);f(#{f(1)}\""#{f(1)}\""#{f("&
            "3)}\""#{f(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f("&
            "1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"" END#{f(1)}\"""&
            "#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f"&
            "(1)}\""34,#{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f"&
            "(1)}\""#{f(3)}\""#{f(1)}\"" CR BYE ; D #{f(1)}\"""&
            "#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f"&
            "(1)}\"" #{f(1)}\""#{f(1)}\"",7);f(#{f(1)}\""#{f(1"&
            ")}\""#{f(3)}\""#{f(1)}\""#{f(1)}\""#{f(1)}\"",7);f"&
            "(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\""#{f(1)}\"&
            """#{f(1)}\"",7);f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{"&
            "f(1)}\"")#{f(1)}\""#{f(1)}\"",3);f(#{f(1)}\""#{f("&
            "1)}\""#{f(3)}\""#{f(1)}\"").#{f(1)}\""#{f(1)}\"",1"&
            ");f(#{f(1)}\""#{f(1)}\""#{f(3)}\""#{f(1)}\"")#{f("&
            "3)}\""#{f(1)}\"")#{f(1)}\""#{f(1)}\"",0);}}]pq#{f"&
            "(1)}\"");}\x60);}\"")""))"&
            " ".
        STOP RUN.
